### ISSUE TITLE
No binary

### ISSUE THREAD

**Issue by brothermechanic** [gpgreen/ShipCAD#4]
Thank you for developedpatch.cpp, now errors gone
But i can't to get executive binary file
i have only /usr/lib/libShipCADlib.a (there is not *.so too)

there are steps of my compilation process
`~/bin/ShipCAD $ /usr/lib64/qt5/bin/qmake EIGEN_ROOT="/usr/include/eigen3" BOOST_ROOT="/usr" -r ShipCAD.pro`
https://paste.pound-python.org/show/iABGGk5mCTs1Vv2X9vWO/
`~/bin/ShipCAD $ make -j 9`
https://paste.pound-python.org/show/JlXvqhDwrNMRJGzPBPg8/
`~/bin/ShipCAD # make install`
https://paste.pound-python.org/show/pp1ARjtPwHVyZ5pNzGJG/

i'm on gentoo lonux, this is gentoo's package full build log
https://paste.pound-python.org/show/u9fd3mf8l5v19I5oNdFJ/

**Comment by gpgreen** [comment]
At this time 'make install' won't do anything as I haven't added installation sections to the qmake .pro files. The GUI was built on line 382 of your log. If you change to that directory and execute it, it should run, unless you don't have OpenGL available. I am not yet checking for that, so probably a crash if that is the case. There are a number of test binaries built as well from your log. There is no shared library, i link it into the executables.

**Comment by brothermechanic** [comment]
Oh, this is still a work in progress. I hope you finish the program so that I can install and run it.
While I will use Freeship on Windows (((

**Comment by brothermechanic** [comment]
ok
i just want to convert my subdivision mesh to nurbs.
FreeShip can do that.
May be you can create simple executable fo it?
If not, ok, waiting whole programm
